name = "Venture"
license = "MIT"
licenselink = "https://github.com/Wtoll/venture/blob/master/LICENSE"
description = "A bold, minimalist theme for Hugo"
homepage = "https://github.com/Wtoll/venture"
tags = [
  "simple",
  "clean",
  "bold",
  "minimalist"
]
features = [
  "responsive",
  "blog",
]
min_version = "0.41.0"

[author]
  name = "William Toll"
  homepage = "https://wtoll.com"

[original]
  author = "Fred Wilson"
  homepage = "https://avc.com"
